name: CD to Prod

# Триггер: пуши в ветку main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🚀 Build & Deploy to Prod
    runs-on: ubuntu-latest
    needs: test
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login \
            ${{ secrets.DOCKER_REGISTRY }} \
            --username "${{ secrets.DOCKER_USER }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          TAG=latest
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:$TAG .

      - name: Push image
        run: |
          TAG=latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:$TAG

      # Этот шаг создаёт в интерфейсе GitHub ожидающий Approval
      - name: Await manual approval
        uses: chrnorm/deployment-approval@v1
        with:
          environment: prod

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /srv/${{ github.repository }} || exit 1
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans
